# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: test
on: workflow_dispatch
jobs:
  build:
    runs-on: macOS-latest
    strategy:
      matrix:
        node-version: [18.7.0]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - name: zipping docs
      run: zip -r dist.zip dist/*
    - name: unzip and copy
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: >-
          cd /data/www/blog/dist &&
          unzip -n  docs.zip
        host: ${{secrets.HOST}}
        username: ${{ secrets.SSH_USER }}
        privateKey: ${{ secrets.PASSWORD }}
